apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secret
  namespace: wordpress
type: Opaque
stringData:
  MYSQL_DATABASE: wordpress
  MySQL_USER: wpuser
  MYSQL_PASSWORD: "BLABLA"
  MYSQL_ROOT_PASSWORD: "BLABLA"
  